ALPACA_KEY_ID = "PKCL0K5PFYA80GL8L6PW"
ALPACA_SECRET_KEY = "kDfKBu2ievCJnljg5UcV37QsVDQHmAWiNBkClUH7"
ALPACA_BASE_URL = "https://paper-api.alpaca.markets/v2"

HEADERS = {
    'APCA-API-KEY-ID' : ALPACA_KEY_ID,
    'APCA-API-SECRET-KEY' : ALPACA_SECRET_KEY
}