on: 
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"

jobs:
  stock-auto:
    runs-on: ubuntu-latest
    env:
      MY_GITHUB_REPO: ${{ github.repository }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-tinytex@v2
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - name: Manually install libsodium
        run: 'sudo apt-get install -y libsodium-dev'
        
      - name: Manually install curl
        run: 'sudo apt-get install -y libcurl4-openssl-dev'
        
      # - name: Manually install httr
      #   run: 'sudo apt-get install -y httr'
      - name: Cache R packages
        uses: actions/cache@v3
        id: cache
        if: runner.os != 'Windows'
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-2-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-2-
    #  - uses: r-lib/actions/setup-renv@v2
      - name: Setup R Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          install.packages('quantmod')
          install.packages('dplyr')
          install.packages('purrr')
          install.packages('TTR')
          install.packages('here')
          install.packages('ggplot2')
          install.packages('plotly')
          install.packages('blastula')

        shell: Rscript {0}

      - name: Check out repository
        uses: actions/checkout@v3
          
      - name: Render document
        run: Rscript -e 'rmarkdown::render(here::here("VisualizeStocks/stock_plots.Rmd"), output_format = "html_document", output_file = "index.html")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull
          git add .
          git commit -m 'Rmarkdown updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
        
